// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `native/include/bluez_media_native.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BluezMediaNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BluezMediaNativeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BluezMediaNativeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ── Client lifecycle ────────────────────────────────────────────────────────
  void bluez_media_init(ffi.Pointer<ffi.Void> dart_api_dl_data) {
    return _bluez_media_init(dart_api_dl_data);
  }

  late final _bluez_media_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_media_init',
      );
  late final _bluez_media_init = _bluez_media_initPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> bluez_media_client_create(int events_port) {
    return _bluez_media_client_create(events_port);
  }

  late final _bluez_media_client_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Int64)>>(
        'bluez_media_client_create',
      );
  late final _bluez_media_client_create = _bluez_media_client_createPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  void bluez_media_client_destroy(ffi.Pointer<ffi.Void> handle) {
    return _bluez_media_client_destroy(handle);
  }

  late final _bluez_media_client_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_media_client_destroy',
      );
  late final _bluez_media_client_destroy = _bluez_media_client_destroyPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// ── org.bluez.Media1 registration ──────────────────────────────────────────
  int bluez_media_register_player(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<BluezMediaPlayerRegistration> registration,
  ) {
    return _bluez_media_register_player(handle, registration);
  }

  late final _bluez_media_register_playerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<BluezMediaPlayerRegistration>,
          )
        >
      >('bluez_media_register_player');
  late final _bluez_media_register_player = _bluez_media_register_playerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<BluezMediaPlayerRegistration>,
        )
      >();

  int bluez_media_unregister_player(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> adapter_path,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_unregister_player(handle, adapter_path, player_path);
  }

  late final _bluez_media_unregister_playerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_unregister_player');
  late final _bluez_media_unregister_player = _bluez_media_unregister_playerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// ── org.bluez.MediaPlayer1 remote controls ─────────────────────────────────
  int bluez_media_player_play(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_play(handle, player_path);
  }

  late final _bluez_media_player_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_play');
  late final _bluez_media_player_play = _bluez_media_player_playPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_pause(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_pause(handle, player_path);
  }

  late final _bluez_media_player_pausePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_pause');
  late final _bluez_media_player_pause = _bluez_media_player_pausePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_stop(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_stop(handle, player_path);
  }

  late final _bluez_media_player_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_stop');
  late final _bluez_media_player_stop = _bluez_media_player_stopPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_next(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_next(handle, player_path);
  }

  late final _bluez_media_player_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_next');
  late final _bluez_media_player_next = _bluez_media_player_nextPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_previous(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_previous(handle, player_path);
  }

  late final _bluez_media_player_previousPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_previous');
  late final _bluez_media_player_previous = _bluez_media_player_previousPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_player_get_properties(
      handle,
      player_path,
      out,
      capacity,
    );
  }

  late final _bluez_media_player_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_player_get_properties');
  late final _bluez_media_player_get_properties =
      _bluez_media_player_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  /// ── org.bluez.MediaControl1 remote controller controls ─────────────────────
  int bluez_media_control_play(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_play(handle, control_path);
  }

  late final _bluez_media_control_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_play');
  late final _bluez_media_control_play = _bluez_media_control_playPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_pause(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_pause(handle, control_path);
  }

  late final _bluez_media_control_pausePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_pause');
  late final _bluez_media_control_pause = _bluez_media_control_pausePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_stop(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_stop(handle, control_path);
  }

  late final _bluez_media_control_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_stop');
  late final _bluez_media_control_stop = _bluez_media_control_stopPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_next(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_next(handle, control_path);
  }

  late final _bluez_media_control_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_next');
  late final _bluez_media_control_next = _bluez_media_control_nextPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_previous(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_previous(handle, control_path);
  }

  late final _bluez_media_control_previousPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_previous');
  late final _bluez_media_control_previous = _bluez_media_control_previousPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_volume_up(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_volume_up(handle, control_path);
  }

  late final _bluez_media_control_volume_upPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_volume_up');
  late final _bluez_media_control_volume_up = _bluez_media_control_volume_upPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_volume_down(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_volume_down(handle, control_path);
  }

  late final _bluez_media_control_volume_downPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_volume_down');
  late final _bluez_media_control_volume_down =
      _bluez_media_control_volume_downPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_control_fast_forward(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_fast_forward(handle, control_path);
  }

  late final _bluez_media_control_fast_forwardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_fast_forward');
  late final _bluez_media_control_fast_forward =
      _bluez_media_control_fast_forwardPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_control_rewind(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_rewind(handle, control_path);
  }

  late final _bluez_media_control_rewindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_rewind');
  late final _bluez_media_control_rewind = _bluez_media_control_rewindPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_control_get_properties(
      handle,
      control_path,
      out,
      capacity,
    );
  }

  late final _bluez_media_control_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_control_get_properties');
  late final _bluez_media_control_get_properties =
      _bluez_media_control_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  /// ── org.bluez.MediaFolder1 browsing ────────────────────────────────────────
  int bluez_media_folder_search(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Char> value,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_folder_search(
      handle,
      folder_path,
      value,
      out,
      capacity,
    );
  }

  late final _bluez_media_folder_searchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_folder_search');
  late final _bluez_media_folder_search = _bluez_media_folder_searchPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  int bluez_media_folder_list_items(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_folder_list_items(handle, folder_path, out, capacity);
  }

  late final _bluez_media_folder_list_itemsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_folder_list_items');
  late final _bluez_media_folder_list_items = _bluez_media_folder_list_itemsPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  int bluez_media_folder_change_folder(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Char> target_folder_path,
  ) {
    return _bluez_media_folder_change_folder(
      handle,
      folder_path,
      target_folder_path,
    );
  }

  late final _bluez_media_folder_change_folderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_folder_change_folder');
  late final _bluez_media_folder_change_folder =
      _bluez_media_folder_change_folderPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  int bluez_media_folder_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_folder_get_properties(
      handle,
      folder_path,
      out,
      capacity,
    );
  }

  late final _bluez_media_folder_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_folder_get_properties');
  late final _bluez_media_folder_get_properties =
      _bluez_media_folder_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  /// ── org.bluez.MediaItem1 browsing ──────────────────────────────────────────
  int bluez_media_item_play(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
  ) {
    return _bluez_media_item_play(handle, item_path);
  }

  late final _bluez_media_item_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_item_play');
  late final _bluez_media_item_play = _bluez_media_item_playPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_item_add_to_now_playing(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
  ) {
    return _bluez_media_item_add_to_now_playing(handle, item_path);
  }

  late final _bluez_media_item_add_to_now_playingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_item_add_to_now_playing');
  late final _bluez_media_item_add_to_now_playing =
      _bluez_media_item_add_to_now_playingPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_item_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_item_get_properties(handle, item_path, out, capacity);
  }

  late final _bluez_media_item_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_item_get_properties');
  late final _bluez_media_item_get_properties =
      _bluez_media_item_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  /// ── org.bluez.MediaTransport1 remote transports ────────────────────────────
  int bluez_media_transport_acquire(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_transport_acquire(
      handle,
      transport_path,
      out,
      capacity,
    );
  }

  late final _bluez_media_transport_acquirePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_transport_acquire');
  late final _bluez_media_transport_acquire = _bluez_media_transport_acquirePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  int bluez_media_transport_try_acquire(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_transport_try_acquire(
      handle,
      transport_path,
      out,
      capacity,
    );
  }

  late final _bluez_media_transport_try_acquirePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_transport_try_acquire');
  late final _bluez_media_transport_try_acquire =
      _bluez_media_transport_try_acquirePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  int bluez_media_transport_release(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
  ) {
    return _bluez_media_transport_release(handle, transport_path);
  }

  late final _bluez_media_transport_releasePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_transport_release');
  late final _bluez_media_transport_release = _bluez_media_transport_releasePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_transport_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_transport_get_properties(
      handle,
      transport_path,
      out,
      capacity,
    );
  }

  late final _bluez_media_transport_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_transport_get_properties');
  late final _bluez_media_transport_get_properties =
      _bluez_media_transport_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  int bluez_media_transport_set_volume(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    int volume,
  ) {
    return _bluez_media_transport_set_volume(handle, transport_path, volume);
  }

  late final _bluez_media_transport_set_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint16,
          )
        >
      >('bluez_media_transport_set_volume');
  late final _bluez_media_transport_set_volume =
      _bluez_media_transport_set_volumePtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, int)
          >();

  int bluez_media_close_fd(int fd) {
    return _bluez_media_close_fd(fd);
  }

  late final _bluez_media_close_fdPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
        'bluez_media_close_fd',
      );
  late final _bluez_media_close_fd = _bluez_media_close_fdPtr
      .asFunction<int Function(int)>();

  /// ── ObjectManager queries ──────────────────────────────────────────────────
  int bluez_media_get_managed_objects(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Uint8> out,
    int capacity,
  ) {
    return _bluez_media_get_managed_objects(handle, out, capacity);
  }

  late final _bluez_media_get_managed_objectsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('bluez_media_get_managed_objects');
  late final _bluez_media_get_managed_objects =
      _bluez_media_get_managed_objectsPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, int)
          >();
}

final class BluezMediaPlayerRegistration extends ffi.Struct {
  external ffi.Pointer<ffi.Char> adapter_path;

  external ffi.Pointer<ffi.Char> player_path;

  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> type;

  external ffi.Pointer<ffi.Char> subtype;

  @ffi.Uint8()
  external int browsable;

  @ffi.Uint8()
  external int searchable;
}
