// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `native/include/bluez_media_native.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BluezMediaNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BluezMediaNativeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BluezMediaNativeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ── Client lifecycle ────────────────────────────────────────────────────────
  void bluez_media_init(ffi.Pointer<ffi.Void> dart_api_dl_data) {
    return _bluez_media_init(dart_api_dl_data);
  }

  late final _bluez_media_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_media_init',
      );
  late final _bluez_media_init = _bluez_media_initPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> bluez_media_client_create(int events_port) {
    return _bluez_media_client_create(events_port);
  }

  late final _bluez_media_client_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Int64)>>(
        'bluez_media_client_create',
      );
  late final _bluez_media_client_create = _bluez_media_client_createPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  void bluez_media_client_create_async(int events_port, int result_port) {
    return _bluez_media_client_create_async(events_port, result_port);
  }

  late final _bluez_media_client_create_asyncPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int64)>>(
        'bluez_media_client_create_async',
      );
  late final _bluez_media_client_create_async =
      _bluez_media_client_create_asyncPtr.asFunction<void Function(int, int)>();

  void bluez_media_client_destroy(ffi.Pointer<ffi.Void> handle) {
    return _bluez_media_client_destroy(handle);
  }

  late final _bluez_media_client_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_media_client_destroy',
      );
  late final _bluez_media_client_destroy = _bluez_media_client_destroyPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Releases data returned through any BluezMediaBuffer and resets its fields.
  void bluez_media_buffer_free(ffi.Pointer<BluezMediaBuffer> buffer) {
    return _bluez_media_buffer_free(buffer);
  }

  late final _bluez_media_buffer_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<BluezMediaBuffer>)>
      >('bluez_media_buffer_free');
  late final _bluez_media_buffer_free = _bluez_media_buffer_freePtr
      .asFunction<void Function(ffi.Pointer<BluezMediaBuffer>)>();

  void bluez_media_call_async(
    ffi.Pointer<ffi.Void> handle,
    int operation,
    ffi.Pointer<ffi.Char> object_path,
    ffi.Pointer<ffi.Char> argument,
    int value,
    int result_port,
  ) {
    return _bluez_media_call_async(
      handle,
      operation,
      object_path,
      argument,
      value,
      result_port,
    );
  }

  late final _bluez_media_call_asyncPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            BluezMediaOperation,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Int64,
          )
        >
      >('bluez_media_call_async');
  late final _bluez_media_call_async = _bluez_media_call_asyncPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
        )
      >();

  /// ── org.bluez.Media1 registration ──────────────────────────────────────────
  int bluez_media_register_player(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<BluezMediaPlayerRegistration> registration,
  ) {
    return _bluez_media_register_player(handle, registration);
  }

  late final _bluez_media_register_playerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<BluezMediaPlayerRegistration>,
          )
        >
      >('bluez_media_register_player');
  late final _bluez_media_register_player = _bluez_media_register_playerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<BluezMediaPlayerRegistration>,
        )
      >();

  void bluez_media_register_player_async(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<BluezMediaPlayerRegistration> registration,
    int result_port,
  ) {
    return _bluez_media_register_player_async(
      handle,
      registration,
      result_port,
    );
  }

  late final _bluez_media_register_player_asyncPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<BluezMediaPlayerRegistration>,
            ffi.Int64,
          )
        >
      >('bluez_media_register_player_async');
  late final _bluez_media_register_player_async =
      _bluez_media_register_player_asyncPtr
          .asFunction<
            void Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<BluezMediaPlayerRegistration>,
              int,
            )
          >();

  int bluez_media_unregister_player(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> adapter_path,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_unregister_player(handle, adapter_path, player_path);
  }

  late final _bluez_media_unregister_playerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_unregister_player');
  late final _bluez_media_unregister_player = _bluez_media_unregister_playerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// ── org.bluez.MediaPlayer1 remote controls ─────────────────────────────────
  int bluez_media_player_play(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_play(handle, player_path);
  }

  late final _bluez_media_player_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_play');
  late final _bluez_media_player_play = _bluez_media_player_playPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_pause(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_pause(handle, player_path);
  }

  late final _bluez_media_player_pausePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_pause');
  late final _bluez_media_player_pause = _bluez_media_player_pausePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_stop(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_stop(handle, player_path);
  }

  late final _bluez_media_player_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_stop');
  late final _bluez_media_player_stop = _bluez_media_player_stopPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_next(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_next(handle, player_path);
  }

  late final _bluez_media_player_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_next');
  late final _bluez_media_player_next = _bluez_media_player_nextPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_previous(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_previous(handle, player_path);
  }

  late final _bluez_media_player_previousPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_previous');
  late final _bluez_media_player_previous = _bluez_media_player_previousPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_fast_forward(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_fast_forward(handle, player_path);
  }

  late final _bluez_media_player_fast_forwardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_fast_forward');
  late final _bluez_media_player_fast_forward =
      _bluez_media_player_fast_forwardPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_player_rewind(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_player_rewind(handle, player_path);
  }

  late final _bluez_media_player_rewindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_player_rewind');
  late final _bluez_media_player_rewind = _bluez_media_player_rewindPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_player_set_repeat(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
    ffi.Pointer<ffi.Char> repeat,
  ) {
    return _bluez_media_player_set_repeat(handle, player_path, repeat);
  }

  late final _bluez_media_player_set_repeatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_player_set_repeat');
  late final _bluez_media_player_set_repeat = _bluez_media_player_set_repeatPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int bluez_media_player_set_shuffle(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
    ffi.Pointer<ffi.Char> shuffle,
  ) {
    return _bluez_media_player_set_shuffle(handle, player_path, shuffle);
  }

  late final _bluez_media_player_set_shufflePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_player_set_shuffle');
  late final _bluez_media_player_set_shuffle =
      _bluez_media_player_set_shufflePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  int bluez_media_player_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_player_get_properties(handle, player_path, out);
  }

  late final _bluez_media_player_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_player_get_properties');
  late final _bluez_media_player_get_properties =
      _bluez_media_player_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<BluezMediaBuffer>,
            )
          >();

  int bluez_media_player_get_cover_art(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
    ffi.Pointer<ffi.Char> target_file,
    int timeout_ms,
  ) {
    return _bluez_media_player_get_cover_art(
      handle,
      player_path,
      target_file,
      timeout_ms,
    );
  }

  late final _bluez_media_player_get_cover_artPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('bluez_media_player_get_cover_art');
  late final _bluez_media_player_get_cover_art =
      _bluez_media_player_get_cover_artPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
            )
          >();

  int bluez_media_player_get_cover_art_from_existing_session(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> player_path,
    ffi.Pointer<ffi.Char> target_file,
    int timeout_ms,
  ) {
    return _bluez_media_player_get_cover_art_from_existing_session(
      handle,
      player_path,
      target_file,
      timeout_ms,
    );
  }

  late final _bluez_media_player_get_cover_art_from_existing_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('bluez_media_player_get_cover_art_from_existing_session');
  late final _bluez_media_player_get_cover_art_from_existing_session =
      _bluez_media_player_get_cover_art_from_existing_sessionPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
            )
          >();

  /// ── org.bluez.MediaControl1 remote controller controls ─────────────────────
  int bluez_media_control_play(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_play(handle, control_path);
  }

  late final _bluez_media_control_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_play');
  late final _bluez_media_control_play = _bluez_media_control_playPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_pause(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_pause(handle, control_path);
  }

  late final _bluez_media_control_pausePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_pause');
  late final _bluez_media_control_pause = _bluez_media_control_pausePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_stop(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_stop(handle, control_path);
  }

  late final _bluez_media_control_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_stop');
  late final _bluez_media_control_stop = _bluez_media_control_stopPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_next(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_next(handle, control_path);
  }

  late final _bluez_media_control_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_next');
  late final _bluez_media_control_next = _bluez_media_control_nextPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_previous(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_previous(handle, control_path);
  }

  late final _bluez_media_control_previousPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_previous');
  late final _bluez_media_control_previous = _bluez_media_control_previousPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_volume_up(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_volume_up(handle, control_path);
  }

  late final _bluez_media_control_volume_upPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_volume_up');
  late final _bluez_media_control_volume_up = _bluez_media_control_volume_upPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_volume_down(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_volume_down(handle, control_path);
  }

  late final _bluez_media_control_volume_downPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_volume_down');
  late final _bluez_media_control_volume_down =
      _bluez_media_control_volume_downPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_control_fast_forward(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_fast_forward(handle, control_path);
  }

  late final _bluez_media_control_fast_forwardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_fast_forward');
  late final _bluez_media_control_fast_forward =
      _bluez_media_control_fast_forwardPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_control_rewind(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
  ) {
    return _bluez_media_control_rewind(handle, control_path);
  }

  late final _bluez_media_control_rewindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_control_rewind');
  late final _bluez_media_control_rewind = _bluez_media_control_rewindPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_control_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> control_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_control_get_properties(handle, control_path, out);
  }

  late final _bluez_media_control_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_control_get_properties');
  late final _bluez_media_control_get_properties =
      _bluez_media_control_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<BluezMediaBuffer>,
            )
          >();

  /// ── org.bluez.MediaFolder1 browsing ────────────────────────────────────────
  int bluez_media_folder_search(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Char> value,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_folder_search(handle, folder_path, value, out);
  }

  late final _bluez_media_folder_searchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_folder_search');
  late final _bluez_media_folder_search = _bluez_media_folder_searchPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<BluezMediaBuffer>,
        )
      >();

  int bluez_media_folder_list_items(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_folder_list_items(handle, folder_path, out);
  }

  late final _bluez_media_folder_list_itemsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_folder_list_items');
  late final _bluez_media_folder_list_items = _bluez_media_folder_list_itemsPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<BluezMediaBuffer>,
        )
      >();

  int bluez_media_folder_change_folder(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Char> target_folder_path,
  ) {
    return _bluez_media_folder_change_folder(
      handle,
      folder_path,
      target_folder_path,
    );
  }

  late final _bluez_media_folder_change_folderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_folder_change_folder');
  late final _bluez_media_folder_change_folder =
      _bluez_media_folder_change_folderPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  int bluez_media_folder_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_folder_get_properties(handle, folder_path, out);
  }

  late final _bluez_media_folder_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_folder_get_properties');
  late final _bluez_media_folder_get_properties =
      _bluez_media_folder_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<BluezMediaBuffer>,
            )
          >();

  /// ── org.bluez.MediaItem1 browsing ──────────────────────────────────────────
  int bluez_media_item_play(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
  ) {
    return _bluez_media_item_play(handle, item_path);
  }

  late final _bluez_media_item_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_item_play');
  late final _bluez_media_item_play = _bluez_media_item_playPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_item_add_to_now_playing(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
  ) {
    return _bluez_media_item_add_to_now_playing(handle, item_path);
  }

  late final _bluez_media_item_add_to_now_playingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_item_add_to_now_playing');
  late final _bluez_media_item_add_to_now_playing =
      _bluez_media_item_add_to_now_playingPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_media_item_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_item_get_properties(handle, item_path, out);
  }

  late final _bluez_media_item_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_item_get_properties');
  late final _bluez_media_item_get_properties =
      _bluez_media_item_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<BluezMediaBuffer>,
            )
          >();

  int bluez_media_item_get_cover_art(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
    ffi.Pointer<ffi.Char> target_file,
    int timeout_ms,
  ) {
    return _bluez_media_item_get_cover_art(
      handle,
      item_path,
      target_file,
      timeout_ms,
    );
  }

  late final _bluez_media_item_get_cover_artPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('bluez_media_item_get_cover_art');
  late final _bluez_media_item_get_cover_art =
      _bluez_media_item_get_cover_artPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
            )
          >();

  int bluez_media_item_get_cover_art_from_existing_session(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> item_path,
    ffi.Pointer<ffi.Char> target_file,
    int timeout_ms,
  ) {
    return _bluez_media_item_get_cover_art_from_existing_session(
      handle,
      item_path,
      target_file,
      timeout_ms,
    );
  }

  late final _bluez_media_item_get_cover_art_from_existing_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('bluez_media_item_get_cover_art_from_existing_session');
  late final _bluez_media_item_get_cover_art_from_existing_session =
      _bluez_media_item_get_cover_art_from_existing_sessionPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
            )
          >();

  /// ── org.bluez.MediaTransport1 remote transports ────────────────────────────
  int bluez_media_transport_acquire(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_transport_acquire(handle, transport_path, out);
  }

  late final _bluez_media_transport_acquirePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_transport_acquire');
  late final _bluez_media_transport_acquire = _bluez_media_transport_acquirePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<BluezMediaBuffer>,
        )
      >();

  int bluez_media_transport_try_acquire(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_transport_try_acquire(handle, transport_path, out);
  }

  late final _bluez_media_transport_try_acquirePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_transport_try_acquire');
  late final _bluez_media_transport_try_acquire =
      _bluez_media_transport_try_acquirePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<BluezMediaBuffer>,
            )
          >();

  int bluez_media_transport_release(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
  ) {
    return _bluez_media_transport_release(handle, transport_path);
  }

  late final _bluez_media_transport_releasePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_media_transport_release');
  late final _bluez_media_transport_release = _bluez_media_transport_releasePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_media_transport_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_transport_get_properties(handle, transport_path, out);
  }

  late final _bluez_media_transport_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<BluezMediaBuffer>,
          )
        >
      >('bluez_media_transport_get_properties');
  late final _bluez_media_transport_get_properties =
      _bluez_media_transport_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<BluezMediaBuffer>,
            )
          >();

  int bluez_media_transport_set_volume(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transport_path,
    int volume,
  ) {
    return _bluez_media_transport_set_volume(handle, transport_path, volume);
  }

  late final _bluez_media_transport_set_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint16,
          )
        >
      >('bluez_media_transport_set_volume');
  late final _bluez_media_transport_set_volume =
      _bluez_media_transport_set_volumePtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, int)
          >();

  int bluez_media_close_fd(int fd) {
    return _bluez_media_close_fd(fd);
  }

  late final _bluez_media_close_fdPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32)>>(
        'bluez_media_close_fd',
      );
  late final _bluez_media_close_fd = _bluez_media_close_fdPtr
      .asFunction<int Function(int)>();

  /// ── ObjectManager queries ──────────────────────────────────────────────────
  int bluez_media_get_managed_objects(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<BluezMediaBuffer> out,
  ) {
    return _bluez_media_get_managed_objects(handle, out);
  }

  late final _bluez_media_get_managed_objectsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<BluezMediaBuffer>)
        >
      >('bluez_media_get_managed_objects');
  late final _bluez_media_get_managed_objects =
      _bluez_media_get_managed_objectsPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<BluezMediaBuffer>)
          >();
}

final class BluezMediaPlayerRegistration extends ffi.Struct {
  external ffi.Pointer<ffi.Char> adapter_path;

  external ffi.Pointer<ffi.Char> player_path;

  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> type;

  external ffi.Pointer<ffi.Char> subtype;

  @ffi.Uint8()
  external int browsable;

  @ffi.Uint8()
  external int searchable;
}

enum BluezMediaStatusCode {
  BLUEZ_MEDIA_SUCCESS(0),
  BLUEZ_MEDIA_ERROR_INVALID_ARGUMENT(-1),
  BLUEZ_MEDIA_ERROR_BUFFER_TOO_SMALL(-2),
  BLUEZ_MEDIA_ERROR_OPERATION_FAILED(-3),
  BLUEZ_MEDIA_ERROR_UNSUPPORTED_SETTING(-4),
  BLUEZ_MEDIA_ERROR_ALREADY_EXISTS(-5),
  BLUEZ_MEDIA_ERROR_NOT_FOUND(-6);

  final int value;
  const BluezMediaStatusCode(this.value);

  static BluezMediaStatusCode fromValue(int value) => switch (value) {
    0 => BLUEZ_MEDIA_SUCCESS,
    -1 => BLUEZ_MEDIA_ERROR_INVALID_ARGUMENT,
    -2 => BLUEZ_MEDIA_ERROR_BUFFER_TOO_SMALL,
    -3 => BLUEZ_MEDIA_ERROR_OPERATION_FAILED,
    -4 => BLUEZ_MEDIA_ERROR_UNSUPPORTED_SETTING,
    -5 => BLUEZ_MEDIA_ERROR_ALREADY_EXISTS,
    -6 => BLUEZ_MEDIA_ERROR_NOT_FOUND,
    _ => throw ArgumentError("Unknown value for BluezMediaStatusCode: $value"),
  };
}

final class BluezMediaBuffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Int32()
  external int length;
}

typedef BluezMediaOperation = ffi.Int32;
typedef DartBluezMediaOperation = int;

const int BLUEZ_MEDIA_OP_PLAYER_PLAY = 0;

const int BLUEZ_MEDIA_OP_PLAYER_PAUSE = 1;

const int BLUEZ_MEDIA_OP_PLAYER_STOP = 2;

const int BLUEZ_MEDIA_OP_PLAYER_NEXT = 3;

const int BLUEZ_MEDIA_OP_PLAYER_PREVIOUS = 4;

const int BLUEZ_MEDIA_OP_PLAYER_FAST_FORWARD = 5;

const int BLUEZ_MEDIA_OP_PLAYER_REWIND = 6;

const int BLUEZ_MEDIA_OP_PLAYER_SET_REPEAT = 7;

const int BLUEZ_MEDIA_OP_PLAYER_SET_SHUFFLE = 8;

const int BLUEZ_MEDIA_OP_PLAYER_GET_PROPERTIES = 9;

const int BLUEZ_MEDIA_OP_PLAYER_GET_COVER_ART = 10;

const int BLUEZ_MEDIA_OP_CONTROL_PLAY = 11;

const int BLUEZ_MEDIA_OP_CONTROL_PAUSE = 12;

const int BLUEZ_MEDIA_OP_CONTROL_STOP = 13;

const int BLUEZ_MEDIA_OP_CONTROL_NEXT = 14;

const int BLUEZ_MEDIA_OP_CONTROL_PREVIOUS = 15;

const int BLUEZ_MEDIA_OP_CONTROL_VOLUME_UP = 16;

const int BLUEZ_MEDIA_OP_CONTROL_VOLUME_DOWN = 17;

const int BLUEZ_MEDIA_OP_CONTROL_FAST_FORWARD = 18;

const int BLUEZ_MEDIA_OP_CONTROL_REWIND = 19;

const int BLUEZ_MEDIA_OP_CONTROL_GET_PROPERTIES = 20;

const int BLUEZ_MEDIA_OP_FOLDER_SEARCH = 21;

const int BLUEZ_MEDIA_OP_FOLDER_LIST_ITEMS = 22;

const int BLUEZ_MEDIA_OP_FOLDER_CHANGE_FOLDER = 23;

const int BLUEZ_MEDIA_OP_FOLDER_GET_PROPERTIES = 24;

const int BLUEZ_MEDIA_OP_ITEM_PLAY = 25;

const int BLUEZ_MEDIA_OP_ITEM_ADD_TO_NOW_PLAYING = 26;

const int BLUEZ_MEDIA_OP_ITEM_GET_PROPERTIES = 27;

const int BLUEZ_MEDIA_OP_TRANSPORT_ACQUIRE = 28;

const int BLUEZ_MEDIA_OP_TRANSPORT_TRY_ACQUIRE = 29;

const int BLUEZ_MEDIA_OP_TRANSPORT_RELEASE = 30;

const int BLUEZ_MEDIA_OP_TRANSPORT_GET_PROPERTIES = 31;

const int BLUEZ_MEDIA_OP_TRANSPORT_SET_VOLUME = 32;

const int BLUEZ_MEDIA_OP_GET_MANAGED_OBJECTS = 33;

const int BLUEZ_MEDIA_OP_UNREGISTER_PLAYER = 34;

const int BLUEZ_MEDIA_OP_PLAYER_GET_COVER_ART_FROM_EXISTING_SESSION = 35;

const int BLUEZ_MEDIA_OP_ITEM_GET_COVER_ART = 36;

const int BLUEZ_MEDIA_OP_ITEM_GET_COVER_ART_FROM_EXISTING_SESSION = 37;
