// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `native/include/bluez_media_native.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BluezMediaNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BluezMediaNativeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BluezMediaNativeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ── Client lifecycle ────────────────────────────────────────────────────────
  ffi.Pointer<ffi.Void> bluez_media_client_create() {
    return _bluez_media_client_create();
  }

  late final _bluez_media_client_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'bluez_media_client_create',
      );
  late final _bluez_media_client_create = _bluez_media_client_createPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void bluez_media_client_destroy(ffi.Pointer<ffi.Void> handle) {
    return _bluez_media_client_destroy(handle);
  }

  late final _bluez_media_client_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_media_client_destroy',
      );
  late final _bluez_media_client_destroy = _bluez_media_client_destroyPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// ── org.bluez.Media1 registration ──────────────────────────────────────────
  int bluez_media_register_player(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<BluezMediaPlayerRegistration> registration,
  ) {
    return _bluez_media_register_player(handle, registration);
  }

  late final _bluez_media_register_playerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<BluezMediaPlayerRegistration>,
          )
        >
      >('bluez_media_register_player');
  late final _bluez_media_register_player = _bluez_media_register_playerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<BluezMediaPlayerRegistration>,
        )
      >();

  int bluez_media_unregister_player(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> adapter_path,
    ffi.Pointer<ffi.Char> player_path,
  ) {
    return _bluez_media_unregister_player(handle, adapter_path, player_path);
  }

  late final _bluez_media_unregister_playerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_media_unregister_player');
  late final _bluez_media_unregister_player = _bluez_media_unregister_playerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They block Dart execution while running, so only use this pattern for work
  /// that is guaranteed to complete quickly.
  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer-lived native function that occupies the calling thread.
  ///
  /// Do not call this kind of function on the main isolate in Flutter apps. Use a
  /// helper isolate for blocking native work.
  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();
}

final class BluezMediaPlayerRegistration extends ffi.Struct {
  external ffi.Pointer<ffi.Char> adapter_path;

  external ffi.Pointer<ffi.Char> player_path;

  external ffi.Pointer<ffi.Char> identity;

  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> type;

  external ffi.Pointer<ffi.Char> subtype;

  external ffi.Pointer<ffi.Char> status;

  @ffi.Uint32()
  external int position_ms;

  @ffi.Uint8()
  external int can_go_next;

  @ffi.Uint8()
  external int can_go_previous;

  @ffi.Uint8()
  external int can_play;

  @ffi.Uint8()
  external int can_pause;

  @ffi.Uint8()
  external int can_seek;

  @ffi.Uint8()
  external int can_control;

  @ffi.Uint8()
  external int browsable;

  @ffi.Uint8()
  external int searchable;
}
